name: Type generation

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate patched Paper jar
        run: |
          curl https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/602/downloads/paper-1.16.5-602.jar >paperclip.jar
          java -jar paperclip.jar || true # Will crash due to missing EULA; we WANT that to happen
          mv cache/patched_1.16.5.jar paper_symbols.jar
      - name: Generate Bungeecord Chat types
        run: |
          java -jar java-ts-bind-all.jar --packageJson bungeecord-chat/package.json
      - name: Generate Paper types
        run: |
          java -jar java-ts-bind-all.jar --packageJson paper/package.json
      - name: Generate WorldEdit types
        run: |
          java -jar java-ts-bind-all.jar --packageJson worldedit/package.json
      - name: Generate WorldGuard types
        run: |
          java -jar java-ts-bind-all.jar --packageJson worldguard/package.json
      - uses: actions/setup-node@master
        with:
          registry-url: 'https://registry.npmjs.org'
        if: github.ref == 'refs/heads/master'
      - name: Publish to npm
        run: |
          sed -i "s/GIT_SHA/$(git rev-parse --short $GITHUB_SHA)/g" */package.json || true # Fails for .github otherwise
          npm publish --access=public bungeecord-chat
          npm publish --access=public paper
          npm publish --access=public worldedit
          npm publish --access=public worldguard
        if: github.ref == 'refs/heads/master'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}